    @startuml

    skinparam style strictuml
    skinparam classAttributeIconSize 0
    skinparam classFontStyle Bold
    hide enum methods

    class Main{
        + main() : int
    }

    package Controller{
        class GameFacade{
            - nextToPlay : Boolean
            
            
            + clickedOnSomeCase(int posX, int posY)
            + play()
            + tare()
            + win()
        }

        
    }

    


    package Model{


        class PieceFactory{
            + createPawn(team : Boolean) : Piece
            + createKing(team : Boolean) : Piece
            + createQueen(team : Boolean) : Piece
            + Bishop(team : Boolean) : Piece
            + createRook(team : Boolean) : Piece
            + createKnight(team : Boolean) : Piece
        }
        

        class Board{
            - allPieceImages : Image[] 
            - whitePts : Integer
            - blackPts : Integer
            - previewCasesMvmt : Boolean[] 
            - previewCasesAtk : Boolean[] 

            + Board() : Board
            + clickedOnSomeCase(int posX, int posY, team Boolean) : Result
            - isCasePreviewMvmt(posX : Integer, posY : Integer) : Boolean
            - isCasePreviewAtk(posX : Integer, posY : Integer) : Boolean
            - isCaseContainPlayerPiece(posX : Integer, posY : Integer, team Boolean) : Boolean
            - movePiece(int oldPosX, int oldPosY, int newPosX, int newPosY)
            - destroyPiece(int posX, int posY)
            - getPiece(int posX, posY)
            - notifyObsPrev()
            - notifyObsEndPrev()
            - notifyObsMov()
            + addObs(obs BoardObserver)
            + initBoard()
            + win(team : Boolean)
            - notifyObsWin(team : Boolean)
            + tare()
            - notifyObsTare()
        }

        
        
        abstract class Piece{
            - chessName : String
            - value : Integer
            - team : Boolean
            - imageLink : String

            + Piece() : Piece 
            + movementBase(piece[] pieces, posX : Integer, posY : Integer) : Boolean[] {abstract}
            + attackMovement(piece[] pieces, posX : Integer, posY : Integer) : Boolean[] {abstract}
            + getTeam() : Boolean
            + getValue() : Integer
            + getChessName() : String
        }

        class Pawn implements Piece{

        }

        class King implements Piece{

        }

        class Queen implements Piece{

        }

        class Bishop implements Piece{

        }

        class Rook implements Piece{

        }

        class Knight implements Piece{

        }

        interface BoardObservers{
            + displayBoard(piece[] pieces) {abstract}
            + displayPreview(Boolean[] previews, Boolean typeMvmt) {abstract}
            + hidePreview() {abstract}
            + displayWin(team: Boolean)
            + displayTare()
            
        }

        Enum Result{
            WIN
            NEXT
            TARE
            NOTHING
        }
    }

    package View{

        'two observers
        'this one is displaying everything with swing
         class DisplayBoard implements BoardObservers{
            + displayBoard(piece[] pieces)
            + displayPreview(Boolean[] previews, Boolean typeMvmt)
            + hidePreview()
            + displayWin(team: Boolean)
            + displayTare()
        }

        class Terminal implements BoardObservers{
            + displayBoard(piece[] pieces)
            + displayPreview(Boolean[] previews, Boolean typeMvmt)
            + hidePreview()
            + displayWin(team: Boolean)
            + displayTare()
        }
    }

    
    

    'Terminal o-> PreviewMovement
   

    GameFacade "1\n board" o-> Board : "own >"
    GameFacade ..> Result : "use >"
    


    Board "pieces\n*" -> Piece : "contains >"

    Board ..> PieceFactory : "uses >"
    Board "*\n observers" o-> BoardObservers : "is observed by"
    Board ..> Result : "use >"
    
    PieceFactory .u.> Pawn : "instantiate >" 
    PieceFactory .u.> King : "instantiate >" 
    PieceFactory .u.> Queen : "instantiate >" 
    PieceFactory .u.> Bishop : "instantiate >" 
    PieceFactory .u.> Rook : "instantiate >" 
    PieceFactory .u.> Knight : "instantiate >" 

    BoardObservers ..|> Board : "Observes"

    Main -d-> GameFacade : "instantiate >"
    Main -d-> DisplayBoard : "instantiate >"
    Main -d-> Terminal : "instantiate >"

    DisplayBoard o-u-> GameFacade : "owns >"




    @enduml